[package]
name = "scx_teddy"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
libbpf-rs = "0.26"

[build-dependencies]
scx_cargo = { git = "https://github.com/sched-ext/scx", branch = "main" }
